### ISSUE TITLE
What about Windows version?

### ISSUE THREAD

**Issue by Oleg26Dev** [petergeoghegan/pg_hexedit#1]
Hi, thank you.
What about Windows version?

**Comment by petergeoghegan** [comment]
Sorry, I don't do Windows. I don't own a Windows machine.

You can probably get it to work on Windows, though, since the program can be compiled on Windows, and the bash script can be run on the Windows Subsystem for Linux. I'm the wrong person to figure out exactly how to do it, though.

If you have a documentation pull request, I'll review it.
